bank/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path("", views.index, name="index"),
    path("admin/", views.admin_view, name="admin"),
    path("manager/", views.manager, name="manager"),
    path("customer_or_manager/", views.customer_or_manager, name="customer_or_manager"),
    path("customer/", views.customer, name="customer"),
    
    path("display_bank_stats/", views.display_bank_stats, name="display_bank_stats"),
    path("display_account_stats/", views.display_account_stats, name="display_account_stats"),
    path("display_corporation_stats/", views.display_corporation_stats, name="display_corporation_stats"),
    path("display_customer_stats/", views.display_customer_stats, name="display_customer_stats"),
    path("display_employee_stats/", views.display_employee_stats, name="display_employee_stats"),
    path("view_stats/", views.view_stats, name="view_stats"),
    
    path("create_bank/", views.create_bank, name="create_bank"),
    path("create_corporation/", views.create_corporation, name="create_corporation"),
    path("start_customer_role/", views.start_customer_role, name="start_customer_role"),
    path("create_fee/", views.create_fee, name="create_fee"),

    path("stop_customer_role/", views.stop_customer_role, name="stop_customer_role"),
    
    path("manage_accounts_admin/", views.manage_accounts_admin, name="manage_accounts"),
    path("manage_accounts_customer/", views.manage_accounts_customer, name="manage_accounts"),
    path("manage_users/", views.manage_users, name="manage_users"),
    path("manage_overdraft/", views.manage_overdraft, name="manage_overdraft"),
    path("remove_accounts_access/", views.remove_accounts_access, name="remove_accounts_access"),
    path("account_deposit/", views.account_deposit, name="account_deposit"),
    path("account_withdrawal/", views.account_withdrawal, name="account_withdrawal"),
    path("account_transfer/", views.account_transfer, name="account_transfer"),

    path("penalize_accounts/", views.penalize_accounts, name="penalize_accounts"),
    path("accrue_interest/", views.accrue_interest, name="accrue_interest"),
    path("pay_employees/", views.pay_employees, name="pay_employees"),

    path("start_employee_role/", views.start_employee_role, name="start_employee_role"),
    path("hire_worker/", views.hire_worker, name="hire_worker"),
    path("stop_employee_role/", views.stop_employee_role, name="stop_employee_role"),

    path("replace_manager/", views.replace_manager, name="replace_manager"),
]

bank/forms.py
from dataclasses import field
from os import access
from django import forms
from .models import *


class CreateBankForm(forms.Form):
    ip_bankid = forms.CharField(label='Bank ID', max_length=100)
    ip_bankname = forms.CharField(label='Name', max_length=100)
    ip_street = forms.CharField(label='Street', max_length=100)
    ip_city = forms.CharField(label='City', max_length=100)
    ip_state = forms.CharField(label='State', max_length=2)
    ip_zip = forms.CharField(label='Zip', max_length=5)
    ip_resassets = forms.IntegerField(label='Reserved Assets')
    ip_corpid = forms.ChoiceField(label='Coporation ID', choices=[(i, i) for i in list(Corporation.objects.all().values_list('corpid', flat=True).distinct())])
    ip_manager = forms.ChoiceField(label='Manger', choices=[(i, i) for i in list(Employee.objects.all().values_list('perid', flat=True).distinct())])
    ip_bank_employee = forms.ChoiceField(label='Employee', choices=[(i, i) for i in list(Employee.objects.all().values_list('perid', flat=True).distinct())])



class CorporationCreationForm(forms.Form):
    ip_corpID = forms.CharField(label='Corporation ID', max_length=100)
    ip_shortName = forms.CharField(label='Short Name', max_length=100)
    ip_longName = forms.CharField(label='Long Name', max_length=100)
    ip_resAssets = forms.CharField(label='Reserved Assets', max_length=50)


class StartCustomerForm(forms.Form):
    ip_perID = forms.CharField(label='Person ID', max_length=100)
    ip_taxID = forms.CharField(label='Tax ID', max_length=11)
    ip_firstName = forms.CharField(label='First name', max_length=100)
    ip_lastName = forms.CharField(label='Last name', max_length=100)
    ip_birthdate = forms.CharField(label='Birthdate', max_length=100)
    ip_street = forms.CharField(label='Street', max_length=100)
    ip_city = forms.CharField(label='City', max_length=100)
    ip_state = forms.CharField(label='State', max_length=2)
    ip_zip = forms.CharField(label='Zip', max_length=5)
    ip_dtJoined = forms.CharField(label='Date joined', max_length=100)
    ip_cust_password = forms.CharField(label='Password', max_length=100)

class StopCustomerForm(forms.Form):
    ip_perID = forms.ChoiceField(label='Person ID', choices=[(i, i) for i in list(Customer.objects.all().values_list('perid', flat=True).distinct())])
    def __init__(self, *args, **kwargs):
        super(StopCustomerForm, self).__init__(*args, **kwargs)
        self.fields['ip_perID'] = forms.ChoiceField(label='Person ID', choices=[(i, i) for i in list(Customer.objects.all().values_list('perid', flat=True).distinct())])

class AccountTransferForm(forms.Form):
    ip_transfer_amount = forms.IntegerField(min_value=0)
    ip_from_bankid = forms.ChoiceField(label='Bank ID', choices=[(i, i) for i in list(Access.objects.all().values_list('bankid', flat=True).distinct())])
    ip_to_bankid = forms.ChoiceField(label='Bank ID', choices=[(i, i) for i in list(Access.objects.all().values_list('bankid', flat=True).distinct())])
    ip_from_accountid = forms.ChoiceField(label='Account ID', choices=[(i, i) for i in list(Access.objects.all().values_list('accountid', flat=True).distinct())])
    ip_to_accountid = forms.ChoiceField(label='Account ID', choices=[(i, i) for i in list(Access.objects.all().values_list('accountid', flat=True).distinct())])

    def __init__(self, *args, **kwargs):
        self._username = kwargs.pop('username', None)
        super(AccountTransferForm, self).__init__(*args, **kwargs)
        if self._username:
            self.fields['ip_from_bankid'] = forms.ChoiceField(label='Bank ID', choices=[(i, i) for i in list(Access.objects.filter(perid=self._username).values_list('bankid', flat=True).distinct())])
            self.fields['ip_from_accountid'] = forms.ChoiceField(label='Account ID', choices=[(i, i) for i in list(Access.objects.filter(perid=self._username).values_list('accountid', flat=True).distinct())])
            self.fields['ip_to_bankid'] = forms.ChoiceField(label='Bank ID', choices=[(i, i) for i in list(Access.objects.filter(perid=self._username).values_list('bankid', flat=True).distinct())])
            self.fields['ip_to_accountid'] = forms.ChoiceField(label='Account ID', choices=[(i, i) for i in list(Access.objects.filter(perid=self._username).values_list('accountid', flat=True).distinct())])

    
class AccountDepositForm(forms.Form):
    ip_deposit_amount = forms.IntegerField(min_value=0)
    ip_bankid = forms.ChoiceField(label='Bank ID', choices=[(i, i) for i in list(Access.objects.all().values_list('bankid', flat=True).distinct())])
    ip_accountid = forms.ChoiceField(label='Account ID', choices=[(i, i) for i in list(Access.objects.all().values_list('accountid', flat=True).distinct())])

    def __init__(self, *args, **kwargs):
        self._username = kwargs.pop('username', None)
        super(AccountDepositForm, self).__init__(*args, **kwargs)
        if self._username:
            self.fields['ip_bankid'] = forms.ChoiceField(label='Bank ID', choices=[(i, i) for i in list(Access.objects.filter(perid=self._username).values_list('bankid', flat=True).distinct())])
            self.fields['ip_accountid'] = forms.ChoiceField(label='Account ID', choices=[(i, i) for i in list(Access.objects.filter(perid=self._username).values_list('accountid', flat=True).distinct())])


class AccountWithdrawalForm(forms.Form):
    ip_withdrawal_amount = forms.IntegerField(min_value=0)
    ip_bankid = forms.ChoiceField(label='Bank ID', choices=[(i, i) for i in list(Access.objects.all().values_list('bankid', flat=True).distinct())])
    ip_accountid = forms.ChoiceField(label='Account ID', choices=[(i, i) for i in list(Access.objects.all().values_list('accountid', flat=True).distinct())])

    def __init__(self, *args, **kwargs):
        self._username = kwargs.pop('username', None)
        super(AccountWithdrawalForm, self).__init__(*args, **kwargs)
        if self._username:
            self.fields['ip_bankid'] = forms.ChoiceField(label='Bank ID', choices=[(i, i) for i in list(Access.objects.filter(perid=self._username).values_list('bankid', flat=True).distinct())])
            self.fields['ip_accountid'] = forms.ChoiceField(label='Account ID', choices=[(i, i) for i in list(Access.objects.filter(perid=self._username).values_list('accountid', flat=True).distinct())])


class CreateFeeForm(forms.Form):
    ip_fee_type = forms.CharField(label='Fee Type', max_length=100)
    ip_bankid = forms.ChoiceField(label='Bank ID', choices=[(i, i) for i in list(Access.objects.all().values_list('bankid', flat=True).distinct())])
    ip_accountid = forms.ChoiceField(label='Account ID', choices=[(i, i) for i in list(Access.objects.all().values_list('accountid', flat=True).distinct())])


class ManageOverdraftForm(forms.Form):
    ip_checking_bankid = forms.ChoiceField(label='Checking Bank ID',choices=[(i, i) for i in list(Checking.objects.all().values_list('bankid', flat=True).distinct())])  
    ip_checking_accountid = forms.ChoiceField(label='Checking Account ID', choices=[(i, i) for i in list(Checking.objects.all().values_list('accountid', flat=True).distinct())])
    ip_add_overdraft = forms.BooleanField(label='Adding Overdraft Policy?', required=False)
    ip_savings_bankid = forms.ChoiceField(label='Saving Bank ID',choices=[(i, i) for i in list(Savings.objects.all().values_list('bankid', flat=True).distinct())])  
    ip_savings_accountid = forms.ChoiceField(label='Saving Account ID',choices=[(i, i) for i in list(Savings.objects.all().values_list('accountid', flat=True).distinct())])  


class AddAccountAccessForm(forms.Form):
    ip_accountID = forms.ChoiceField(label='Accessible Accounts', choices=[(i, i) for i in list(BankAccount.objects.all().values_list('accountid', flat=True).distinct())])
    ip_customer = forms.ChoiceField(label='Customer', choices=[(i, i) for i in list(Customer.objects.all().values_list('perid', flat=True).distinct())])
    ip_add_account_access = forms.BooleanField(label='Adding Owner?')


class StartEmployeeForm(forms.Form):
    ip_perID = forms.CharField(label='Person ID', max_length=100)
    ip_taxID = forms.CharField(label='Tax ID', max_length=11)
    ip_firstName = forms.CharField(label='First name', max_length=100)
    ip_lastName = forms.CharField(label='Last name', max_length=100)
    ip_birthdate = forms.DateField(label='Birth Date')
    ip_street = forms.CharField(label='Street', max_length=100)
    ip_city = forms.CharField(label='City', max_length=100)
    ip_state = forms.CharField(label='State', max_length=2)
    ip_zip = forms.CharField(label='Zip', max_length=5)
    ip_dtJoined = forms.DateField(label='Date Joined')
    ip_salary = forms.IntegerField(label='Salary', min_value=0)
    ip_payments = forms.IntegerField(label='Number of Payments', min_value=0)
    ip_earned = forms.IntegerField(label='Earned', min_value=0)
    emp_password = forms.CharField(label='Password', max_length=100)


class HireWorkerForm(forms.Form):
    ip_perid = forms.ChoiceField(label='Person ID', choices=[(i, i) for i in list(Employee.objects.all().values_list('perid', flat=True).distinct())])
    ip_bankid = forms.ChoiceField(label='Bank ID', choices=[(i, i) for i in list(Bank.objects.all().values_list('bankid', flat=True).distinct())])
    ip_salary = forms.IntegerField(label='Salary', min_value=0)
    

class StopEmployeeForm(forms.Form):
    ip_perID = forms.ChoiceField(label='Person ID', choices=[(i, i) for i in list(Employee.objects.all().values_list('perid', flat=True).distinct())])
    
    def __init__(self, *args, **kwargs):
        super(StopEmployeeForm, self).__init__(*args, **kwargs)
        self.fields['ip_perID'] = forms.ChoiceField(label='Person ID', choices=[(i, i) for i in list(Employee.objects.all().values_list('perid', flat=True).distinct())])


class ReplaceManagerForm(forms.Form):
    ip_bankID = forms.ChoiceField(label='Bank', choices=[(i, i) for i in list(Bank.objects.all().values_list('bankid', flat=True).distinct())])

templates/bank/account_deposit.html
<!DOCTYPE html>
<html>
    <head>
        <title>
            Account Deposit
        </title>
    </head>
    <body>
        <center>
            <h1>
                Account Deposit
            </h1>
            <hr/>
            <form method="POST" > {% csrf_token %}
                Amount <br>
                {{form1.ip_deposit_amount}} <br>
                To: <br> 
                {{form1.ip_bankid}}
                {{form1.ip_accountid}} <br> <br>
                <input type="submit" value="deposit" />
            </form>
            {% if messages %}
                {% for displaydata in messages %}
                <h3 style="color: green;">{{ displaydata }}</h3>
                {% endfor %}
            {% endif %}
            <h3>
                <a href="../">Back to Menu</a>
            </h3>
        </center>
        <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
        <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
        <script>
            $(document).ready(function() {
                $('#id_ip_bankid').select2();
                $('#id_ip_accountid').select2();
            });
        </script>
        <style>
            #id_ip_bankid {
                width: 10%
            }
            #id_ip_accountid {
                width: 15%
            }
        </style>
    </body>
</html>

templates/bank/account_transfer.html
<!DOCTYPE html>
<html>
    <head>
        <title>
            Account Transfer
        </title>
    </head>
    <body>
        <center>
            <h1>
                Account Transfer
            </h1>
            <hr/>
            <form method="POST"> {% csrf_token %}
                Amount <br>
                {{form1.ip_transfer_amount}} <br>
                From: <br>  
                {{form1.ip_from_bankid}}
                {{form1.ip_from_accountid}} <br>
                To: <br>
                {{form1.ip_to_bankid}}
                {{form1.ip_to_accountid}} <br> <br>
                <input type="submit" value="Transfer" />
            </form>
            {% if messages %}
                {% for displaydata in messages %}
                <h3 style="color: red;">{{ displaydata }}</h3>
                {% endfor %}
            {% endif %}
            <h3>
                <a href="../">Back to Menu</a>
            </h3>
        </center>
        <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
        <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
        <script>
            $(document).ready(function() {
                $('#id_ip_from_bankid').select2();
                $('#id_ip_from_accountid').select2();
                $('#id_ip_to_bankid').select2();
                $('#id_ip_to_accountid').select2();
            });
        </script>
        <style>
            #id_ip_from_bankid {
                width: 10%
            }
            #id_ip_from_accountid {
                width: 15%
            }
            #id_ip_to_bankid {
                width: 10%
            }
            #id_ip_to_accountid {
                width: 15%
            }
        </style>
    </body>
</html>

templates/bank/accrue_interest.html
<!DOCTYPE html>
<html>
    <head>
        <title>
            Accrue interest
        </title>
    </head>
    <body>
        <center>
            <h1>
                Accrue interest
            </h1>
            <hr/>
            {% if messages %}
                {% for displaydata in messages %}
                <h3 style="color: green;">{{ displaydata }}</h3>
                {% endfor %}
            {% endif %}
            <h3>
                <a href="../">Back to Menu</a>
            </h3>
        </center>

    </body>
</html>

templates/bank/admin.html
<!DOCTYPE html>
<html>
    <head>
        <title>
            Bank of CS 4400 - Admin Page
        </title>
        <center>
            <h1>
                Bank of CS 4400 - Admin Page
            </h1>
            <h2>
                Welcome, {{ username }}! <a href="/accounts/logout">Logout</a>
            </h2>
            <h3>
                <a href="/bank/view_stats">View Stats</a>   <br>
                <a href="/bank/manage_overdraft">Manage Overdraft</a>   <br>
                <a href="/bank/manage_users">Manage Users</a>   <br>
                <a href="/bank/create_corporation">Create Corporation</a>   <br>
                <a href="/bank/create_bank">Create Bank</a>   <br>
                <a href="/bank/create_fee">Create Fee</a>   <br>
                <a href="/bank/penalize_accounts">Penalize Accounts</a>    <br>
                <a href="/bank/accrue_interest">Accrue Interest</a>    <br>
                <a href="/bank/pay_employees">Pay Employee</a>   <br>
                <a href="/bank/replace_manager">Replace Manager</a>   <br>
                <a href="/bank/manage_accounts_admin">Add Account Access</a>   <br>
                <a href="/bank/remove_accounts_access">Remove Account Access</a>   <br>
            </h3>
        </center>

    </head>
</html>

templates/bank/create_corporation.html
<!DOCTYPE html>
<html>
    <head>
        <title>
            Create Corporation
        </title>
    </head>
    <body>
        <center>
            <h1>
                Create Corporation
            </h1>
            <hr/>
            <form method="POST"> {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="Save" />
            </form>
            {% if messages %}
                {% for displaydata in messages %}
                <h3 style="color: red;">{{ displaydata }}</h3>
                {% endfor %}
            {% endif %}
            <h3>
                <a href="../">Back to Menu</a>
            </h3>
        </center>

    </body>
</html>

templates/bank/customer.html
<!DOCTYPE html>
<html>
    <head>
        <title>
            Bank of CS 4400
        </title>
        <center>
            <h1>
                Bank of CS 4400 - Customer Page
            </h1>
            <h2>
                Welcome, {{ username }}! <a href="/accounts/logout">Logout</a>
            </h2>
            <h3>
            
                <a href="/bank/account_deposit">Account Deposit</a> <br>
                <a href="/bank/account_withdrawal">Account Withdrawal</a> <br>
                <a href="/bank/account_transfer">Account Transfer</a>   <br>
                <a href="/bank/manage_overdraft">Manage Overdraft</a>   <br>
                <a href="/bank/manage_accounts_customer">Manage Accounts Access</a>   <br>
            </h3>
        </center>

    </head>
</html>

templates/bank/display_bank_stats.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title>
            {{ title }}
        </title>
    </head>
    <body>
        <center>
            <h1>
                {{ title }}
            </h1>
            <table border="1" id="bank_stats_table", class="display">
                <thead>
                    <tr>
                        {% for column in columns %}
                        <th>{{ column }}</th>
                        {% endfor %}
                    </tr>
                </thead>
                <tbody>
                    {% for result in results %}
                    <tr>
                        {% for field in result %}
                        <th>{{field}}</th>
                        {% endfor %}
                    </tr>
                    {% endfor %}
                </tbody>
                
            </table>
            <h3>
                <a href="../">Back to Menu</a>
            </h3>
        </center>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.5/css/jquery.dataTables.min.css">
        <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
        <script>
            $(document).ready( function () {
                $('#bank_stats_table').DataTable();
            } );
        </script>
    </body>
</html>

templates/bank/manage_accounts_customer.html
<!DOCTYPE html>
<html>
    <head>
        <title>
            Manage Accounts (Customer)
        </title>
    </head>
    <body>
        <center>
            <h1>
                Manage Accounts (Customer)
            </h1>
            <hr/>
            <form method="POST"> {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="Save" />
            </form>
            {% if messages %}
                {% for displaydata in messages %}
                <h3 style="color: red;">{{ displaydata }}</h3>
                {% endfor %}
            {% endif %}
            <h3>
                <a href="../">Back to Menu</a>
            </h3>
        </center>
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script>
        $(document).ready(function() {
            $('#id_ip_customer').select2();
            $('#id_ip_bankid').select2();
            $('#id_ip_accountid').select2();
        });
    </script>
    <style>
        #id_ip_customer {
            width: 10%
        }
        #id_ip_bankid{
            width:10%
        }
        #id_ip_accountid{
            width:10%
        }
    </style>
    </body>
</html>

templates/bank/manage_users.html
<!DOCTYPE html>
<html>
    <head>
        <title>
            Manage Users
        </title>
        <center>
            <h1>
                Manage Users
            </h1>
            <h3>
                <a href="/bank/start_employee_role">Start Employee Role</a>   <br>
                <a href="/bank/start_customer_role">Start Customer Role</a>   <br>
                <a href="/bank/stop_employee_role">Stop Employee Role</a>   <br>
                <a href="/bank/stop_customer_role">Stop Customer Role</a>   <br>
            </h3>
            <h3>
                <a href="../">Back to Menu</a>
            </h3>
        </center>

    </head>
</html>

templates/bank/pay_employees.html
<!DOCTYPE html>
<html>
    <head>
        <title>
            Pay Employees
        </title>
    </head>
    <body>
        <center>
            <h1>
                Pay Employees
            </h1>
            <hr/>
            {% if messages %}
                {% for displaydata in messages %}
                <h3 style="color: green;">{{ displaydata }}</h3>
                {% endfor %}
            {% endif %}
            <h3>
                <a href="../">Back to Menu</a>
            </h3>
        </center>

    </body>
</html>

templates/bank/remove_accounts_access.html
<!DOCTYPE html>
<html>
    <head>
        <title>
            Remove Account Access (Admin)
        </title>
    </head>
    <body>
        <center>
            <h1>
                Remove Account Access (Admin)
            </h1>
            <hr/>
            <form method="POST"> {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="Save" />
            </form>
            {% if messages %}
                {% for displaydata in messages %}
                <h3 style="color: red;">{{ displaydata }}</h3>
                {% endfor %}
            {% endif %}
            <h3>
                <a href="../">Back to Menu</a>
            </h3>
        </center>
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script>
        $(document).ready(function() {
            $('#id_ip_customer').select2();
            $('#id_ip_bankid').select2();
            $('#id_ip_accountid').select2();
        });
    </script>
    <style>
        #id_ip_customer {
            width: 10%
        }
    </style>

    </body>
</html>

templates/bank/start_employee_role.html
<!DOCTYPE html>
<html>
    <head>
        <title>
            Create Employee Role
        </title>
    </head>
    <body>
        <center>
            <h1>
                Create Employee Role
            </h1>
            <hr/>
            <form method="POST"> {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="Save" />
            </form>
            {% if messages %}
                {% for displaydata in messages %}
                <h3 style="color: red;">{{ displaydata }}</h3>
                {% endfor %}
            {% endif %}
            <h3>
                <a href="../">Back to Menu</a>
            </h3>
        </center>

    </body>
</html>

templates/bank/stop_employee_role.html
<!DOCTYPE html>
<html>
    <head>
        <title>
            Stop employee role
        </title>
    </head>
    <body>
        <center>
            <h1>
                Stop employee role
            </h1>
            <hr/>
            <form method="POST"> {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="Save" />
            </form>
            {% if messages %}
                {% for displaydata in messages %}
                <h3 style="color: red;">{{ displaydata }}</h3>
                {% endfor %}
            {% endif %}
            <h3>
                <a href="../">Back to Menu</a>
            </h3>
        </center>
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script>
        $(document).ready(function() {
            $('#id_ip_perID').select2();
        });
    </script>
    <style>
        
        #id_ip_perID {
            width: 10%
        }
        
    </style>
    </body>
</html>

templates/bank/view_stats.html
<!DOCTYPE html>
<html>
    <head>
        <title>
            Bank of CS 4400
        </title>
        <center>
            <h1>
                View Stats
            </h1>
            <h3>
                <a href="/bank/display_bank_stats">Display Bank Stats</a> <br>
                <a href="/bank/display_account_stats">Display Account Stats</a> <br>
                <a href="/bank/display_corporation_stats">Display Corporation Stats</a> <br>
                <a href="/bank/display_customer_stats">Display Customer Stats</a> <br>
                <a href="/bank/display_employee_stats">Display Employee Stats</a> <br>
            </h3>
            <h3>
                <a href="../">Back to Menu</a>
            </h3>
        </center>
    </head>
</html>